# Generated by Django 4.0 on 2021-12-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debuff',
            name='potency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
