# Generated by Django 4.0 on 2021-12-29 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('action_type', models.CharField(choices=[('weaponskill', 'Weaponskill'), ('ability', 'Ability')], max_length=200, null=True)),
                ('cast_time', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('recast_time', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('potency', models.IntegerField(null=True)),
                ('combo_potency', models.IntegerField(null=True)),
                ('combo_action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='action.action')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
        ),
    ]
