# Generated by Django 4.0 on 2021-12-29 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='combo_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='action.action'),
        ),
        migrations.AlterField(
            model_name='action',
            name='combo_potency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='potency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
