# Generated by Django 4.0 on 2021-12-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_group',
            field=models.CharField(choices=[('tank', 'Tank'), ('healer', 'Healer'), ('dps', 'DPS')], max_length=200, null=True),
        ),
    ]
